/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBaluniV1Agent,
  IBaluniV1AgentInterface,
} from "../../../contracts/interfaces/IBaluniV1Agent";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct IBaluniV1Agent.Call[]",
        name: "calls",
        type: "tuple[]",
      },
      {
        internalType: "address[]",
        name: "tokensReturn",
        type: "address[]",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBaluniV1Agent__factory {
  static readonly abi = _abi;
  static createInterface(): IBaluniV1AgentInterface {
    return new Interface(_abi) as IBaluniV1AgentInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBaluniV1Agent {
    return new Contract(address, _abi, runner) as unknown as IBaluniV1Agent;
  }
}
