/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "USDC_TO_USDT_RATE"
      | "USDC_TO_WBTC_RATE"
      | "USDC_TO_WETH_RATE"
      | "USDC_TO_WMATIC_RATE"
      | "USDT_TO_USDC_RATE"
      | "USDT_TO_WBTC_RATE"
      | "USDT_TO_WETH_RATE"
      | "USDT_TO_WMATIC_RATE"
      | "WBTC_TO_USDC_RATE"
      | "WBTC_TO_USDT_RATE"
      | "WBTC_TO_WETH_RATE"
      | "WBTC_TO_WMATIC_RATE"
      | "WETH_TO_USDC_RATE"
      | "WETH_TO_USDT_RATE"
      | "WETH_TO_WBTC_RATE"
      | "WETH_TO_WMATIC_RATE"
      | "WMATIC_TO_USDC_RATE"
      | "WMATIC_TO_USDT_RATE"
      | "WMATIC_TO_WBTC_RATE"
      | "WMATIC_TO_WETH_RATE"
      | "WNATIVE"
      | "convert"
      | "convertScaled"
      | "rates"
      | "treasury"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "USDC_TO_USDT_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDC_TO_WBTC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDC_TO_WETH_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDC_TO_WMATIC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_TO_USDC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_TO_WBTC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_TO_WETH_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_TO_WMATIC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WBTC_TO_USDC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WBTC_TO_USDT_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WBTC_TO_WETH_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WBTC_TO_WMATIC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WETH_TO_USDC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WETH_TO_USDT_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WETH_TO_WBTC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WETH_TO_WMATIC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WMATIC_TO_USDC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WMATIC_TO_USDT_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WMATIC_TO_WBTC_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WMATIC_TO_WETH_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WNATIVE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "convert",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertScaled",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rates",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "USDC_TO_USDT_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDC_TO_WBTC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDC_TO_WETH_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDC_TO_WMATIC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_TO_USDC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_TO_WBTC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_TO_WETH_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_TO_WMATIC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WBTC_TO_USDC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WBTC_TO_USDT_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WBTC_TO_WETH_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WBTC_TO_WMATIC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WETH_TO_USDC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WETH_TO_USDT_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WETH_TO_WBTC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WETH_TO_WMATIC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WMATIC_TO_USDC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WMATIC_TO_USDT_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WMATIC_TO_WBTC_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WMATIC_TO_WETH_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WNATIVE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "convert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertScaled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rates", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export interface MockOracle extends BaseContract {
  connect(runner?: ContractRunner | null): MockOracle;
  waitForDeployment(): Promise<this>;

  interface: MockOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  USDC_TO_USDT_RATE: TypedContractMethod<[], [bigint], "view">;

  USDC_TO_WBTC_RATE: TypedContractMethod<[], [bigint], "view">;

  USDC_TO_WETH_RATE: TypedContractMethod<[], [bigint], "view">;

  USDC_TO_WMATIC_RATE: TypedContractMethod<[], [bigint], "view">;

  USDT_TO_USDC_RATE: TypedContractMethod<[], [bigint], "view">;

  USDT_TO_WBTC_RATE: TypedContractMethod<[], [bigint], "view">;

  USDT_TO_WETH_RATE: TypedContractMethod<[], [bigint], "view">;

  USDT_TO_WMATIC_RATE: TypedContractMethod<[], [bigint], "view">;

  WBTC_TO_USDC_RATE: TypedContractMethod<[], [bigint], "view">;

  WBTC_TO_USDT_RATE: TypedContractMethod<[], [bigint], "view">;

  WBTC_TO_WETH_RATE: TypedContractMethod<[], [bigint], "view">;

  WBTC_TO_WMATIC_RATE: TypedContractMethod<[], [bigint], "view">;

  WETH_TO_USDC_RATE: TypedContractMethod<[], [bigint], "view">;

  WETH_TO_USDT_RATE: TypedContractMethod<[], [bigint], "view">;

  WETH_TO_WBTC_RATE: TypedContractMethod<[], [bigint], "view">;

  WETH_TO_WMATIC_RATE: TypedContractMethod<[], [bigint], "view">;

  WMATIC_TO_USDC_RATE: TypedContractMethod<[], [bigint], "view">;

  WMATIC_TO_USDT_RATE: TypedContractMethod<[], [bigint], "view">;

  WMATIC_TO_WBTC_RATE: TypedContractMethod<[], [bigint], "view">;

  WMATIC_TO_WETH_RATE: TypedContractMethod<[], [bigint], "view">;

  WNATIVE: TypedContractMethod<[], [string], "view">;

  convert: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  convertScaled: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  rates: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDC_TO_USDT_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC_TO_WBTC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC_TO_WETH_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC_TO_WMATIC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDT_TO_USDC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDT_TO_WBTC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDT_TO_WETH_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDT_TO_WMATIC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WBTC_TO_USDC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WBTC_TO_USDT_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WBTC_TO_WETH_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WBTC_TO_WMATIC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WETH_TO_USDC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WETH_TO_USDT_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WETH_TO_WBTC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WETH_TO_WMATIC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WMATIC_TO_USDC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WMATIC_TO_USDT_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WMATIC_TO_WBTC_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WMATIC_TO_WETH_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WNATIVE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "convert"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "convertScaled"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "rates"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
