/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IBaluniV1PoolRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllPools"
      | "getPoolByAssets"
      | "getPoolsByAsset"
      | "poolExist"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolByAssets",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolsByAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolExist",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolByAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolsByAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolExist", data: BytesLike): Result;
}

export interface IBaluniV1PoolRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IBaluniV1PoolRegistry;
  waitForDeployment(): Promise<this>;

  interface: IBaluniV1PoolRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllPools: TypedContractMethod<[], [string[]], "view">;

  getPoolByAssets: TypedContractMethod<
    [asset1: AddressLike, asset2: AddressLike],
    [string],
    "view"
  >;

  getPoolsByAsset: TypedContractMethod<
    [token: AddressLike],
    [string[]],
    "view"
  >;

  poolExist: TypedContractMethod<[_pool: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllPools"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPoolByAssets"
  ): TypedContractMethod<
    [asset1: AddressLike, asset2: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolsByAsset"
  ): TypedContractMethod<[token: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "poolExist"
  ): TypedContractMethod<[_pool: AddressLike], [boolean], "view">;

  filters: {};
}
